from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from profile_backend.domain.models import DraftMode, ResolvedBundle


class BundleGateway(Protocol):
    def resolve(self, bundle_input: str | Path, output_dir: str | Path) -> ResolvedBundle: ...


class CoverageGateway(Protocol):
    def analyze(self, bundle: dict[str, Any]) -> dict[str, Any]: ...


class DraftingGateway(Protocol):
    def build_preview(self, bundle: dict[str, Any], coverage: dict[str, Any]) -> dict[str, Any]: ...

    def build_template(self, bundle: dict[str, Any], coverage: dict[str, Any]) -> dict[str, Any]: ...

    def build_live(self, bundle: dict[str, Any], coverage: dict[str, Any]) -> dict[str, Any]: ...


class WorkspacePackageGateway(Protocol):
    def build_docs_package(
        self, bundle: dict[str, Any], coverage: dict[str, Any], draft: dict[str, Any]
    ) -> dict[str, Any]: ...

    def build_sheets_package(
        self, bundle: dict[str, Any], coverage: dict[str, Any], draft: dict[str, Any]
    ) -> dict[str, Any]: ...


class JsonStorageGateway(Protocol):
    def save(self, path: str | Path, payload: Any) -> Path: ...

    def load(self, path: str | Path) -> dict[str, Any]: ...


class UserTokenGateway(Protocol):
    def save(self, analyst_id: str, payload: dict[str, Any]) -> Path: ...

    def load(self, analyst_id: str) -> dict[str, Any] | None: ...

    def delete(self, analyst_id: str) -> None: ...

    def exists(self, analyst_id: str) -> bool: ...

    def resolve_path(self, analyst_id: str) -> Path: ...


class OAuthProviderGateway(Protocol):
    def build_authorization_url(self) -> tuple[str, str]: ...

    def exchange_code(self, state: str, code: str) -> dict[str, Any]: ...

    def refresh_authorized_user_info(self, authorized_user_info: dict[str, Any]) -> dict[str, Any]: ...

    def revoke(self, token: str) -> None: ...


class WorkspacePublisherGateway(Protocol):
    def publish_document(self, authorized_user_info: dict[str, Any], package: dict[str, Any]) -> dict[str, Any]: ...

    def publish_spreadsheet(self, authorized_user_info: dict[str, Any], package: dict[str, Any]) -> dict[str, Any]: ...
